meta:
  app_id: opal_tool_sample_app
  display_name: Sample Opal tool app
  version: 1.0.0-dev.12
  vendor: optimizely
  summary: Opal tool to estimate time to run an experiment
  support_url: https://support.optimizely.com
  contact_email: support@optimizely.com
  categories:
    - Personalization & Content
  availability:
    - all

runtime: node22

functions:
  opal_tool:
    entry_point: OpalToolFunction
    description: Opal tool function
  another_opal_tool: 
    entry_point: AnotherOpalToolFunction
    description: AnotherOpal tool function
  
